export const TRUTH_OR_DATE = {
    Hot: {
        Truth: [
            'What is your favorite type of porn?',
            'What’s a sex position we have never attempted that you would like to try?',
            'What is the most embarrassing thing in your search history?',
            'Have you ever peed in a pool?',
            'What’s the longest amount of time you have gone without sex?',
            'What is your wildest sexual fantasy?',
            'What is your sweet spot?',
            'Have you ever faked an orgasm?',
            'What would be more thrilling: angry sex or make-up sex?',
            'Who do you think is secretly gay?',
            'What is the weirdest thing you have done in public?',
            'What’s the most embarrassing thing that’s happened to you during sex?',
            'Lights on or lights off?',
            'Your biggest shame in bed?',
            'Could you have sex with someone of the same gender?',
            'Have you ever been aroused at work?',
            'What’s the most flexible sex move you can do?',
            'Do you like loud or silent people in bed?',
            'What is your favourite song when it comes to action in the bedroom?',
            'Imagine we’re having sex at your workplace. Describe the scene.',
            'What’s your biggest turn off?',
            'Spit or Swallow?',
        ],
        Dare: [
            'Tell the story of your first time in a sexy voice.',
            'Send your ex a message saying you miss them.',
            'Seductively eat a banana whilst locking eyes with the person to your left.',
            'Rub on your nipples until they become hard.',
            'Talk to your hand like you’re making a game plan to sleep with someone else who is in the room.',
            'Perform a seductive dance in front of the group.',
            'Drop an ice cube in your pants.',
            'Make your orgasm face at the next stranger you see until they make eye contact with you.',
            'Send one of your parents a sext and don’t reply to them for one hour.',
            'Take a strawberry and eat it with your partner together.',
            'Show the most embarrassing photo on your phone',
            'Smell everyone’s armpits and rank them from best to worst.',
            'Update your Facebook or Twitter status to "I am horny!".',
            'Moan as loud as you can without laughing.',
            'Take your pants off for the rest of the round.',
            'Get on the table (or in the middle/front) and do a strip tease.',
            'Ask a stranger for advice on a strange rash you’ve recently developed.',
            'Pick up the nearest object to you and demonstrate how to put on protection.',
            'Sit on the lap of the person to your right with no clothes on.',
        ]
    },
    Date: {
        Truth: [
            'How far would you go on a first date?',
            'What is your opinion on love bites, do you want to give me any?',
            'Would you ever sleep with your ex’s best friend?',
            'What is the biggest turn off in a partner?',
            'What is the difference to you between sex and making love?',
            'What is your favorite sex position?',
            'Have you ever been in a friends with benefits situation?',
            'What’s something about your last relationship that you could have improved?',
            'If you had to choose between dating someone ugly who was good in bed or dating someone hot who was bad in bed, which would you choose?',
            'What do you wear to bed when you are in the mood?',
            'What is the most attractive quality in a partner?',
            'Describe your idea of a perfect date.',
            'Have you ever had a one night stand?',
            'Do you like experimenting with different positions, which is your favorite?',
            'What’s the best feature of the question asker?',
            'What do you value most in a relationship?',
            'Best date you’ve ever been on?',
            'Worst date you’ve ever been on?',
            'What part of your body do you enjoy the most on a women/men?',
            'Do you prefer to give or receive?',
            'What is the weirdest thing you dreamt of doing with a girl/boy?',
            'What’s your #1 sex jam?',
        ],
        Dare: [
            'Show me the last thing you searched for on Google.',
            'Paint a picture using only your feet.',
            'Sing the national anthem in a funny accent.',
            'Try to make me laugh in 5 minutes.',
            'Sing a song like an opera singer.',
            'Eat a clove of raw garlic without reacting.',
            'Act like an animal of my choice for 10 minutes.',
            'Take off my shirt without using your hands.',
            'Break an egg on your head.',
            'Say the alphabet backward as fast as you can.',
            'Let me post on your social media and pretend to be you.',
            'Hold three ice cubes in your mouth until they melt.',
            'Eat a spoonful of mustard.',
            'Let me do your makeup while I’m blindfolded.',
            'Tell me your worst pickup line.',
            'Take a shot of apple cider vinegar.',
            'Take a bath with your clothes on.',
            'Show me the most unflattering picture of you.',
            'Call up your local pizza place and try to order a hamburger.',
            'Yell the first word that comes to your mind.',
            'Take a bite of a stick of butter.',
            'Do the worm!',
            'Twerk to your least favorite song.',
            'Do your best impression of me.',
            'Put on as many layers of clothes as possible in 60 seconds.',
            'Open the fridge 20 times in 20 fabulous different ways.',
            'Take a shot of pickle juice.',
            'Try to lick your elbow.',
            'Close your eyes and send a text to someone random.',
            'Make out with a pillow.',
            'Do a seductive dance on the table.',
            'Show me an adult video of something you’d like to try together.',
            'Turn off the lights and try to turn me on only through sounds.',
            'Lick something off of me.',
            'Be intimate with me in a new part of the house.',
            'Leave an R-rated voicemail for me to listen to later.',
            'Send me the spiciest text message you can think of.',
            'Give me a lap dance.',
            'Eat a strawberry in the most sensual way possible.',
            'Let me draw you naked.',
            'Do a spicy dance to a song I choose.',
            'Play a round of seven minutes in heaven with me.',
            'Pretend to be a sports commentator and describe our last sexy night in explicit detail.',
            'Give me a massage.',
            'Do your best sexy crawl.',
            'Pretend you won an award for the best sex performance and give your best acceptance speech.',
            'Wear one of my pieces of clothing for the rest of the game, but I get to pick what it is and how you wear it.',
            'Use your elbows to unbuckle your belt',
        ]
    },
    Party: {
        Truth: [],
        Dare: []
    }
}